//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen1NETWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int ID { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Producto { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
